# Generated by Django 3.0.9 on 2021-01-31 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20210131_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='user_name',
            new_name='customer',
        ),
    ]
