# Generated by Django 3.0.9 on 2021-02-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20210209_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reserved', 'Reserved'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
