# Generated by Django 3.0.9 on 2021-02-14 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='Order',
            new_name='order',
        ),
    ]
